// Generated by scripts/generate-api-types.mjs from openapi.json. Do not edit; run `just types`.
export interface paths {
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Root
     * @description Root endpoint.
     */
    get: operations['root__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/conversations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Conversations
     * @description List the caller's threads scoped to one paper, most recently updated first.
     *
     *     Every conversation is paper-scoped (Phase 3), so the paper is required.
     */
    get: operations['list_conversations_api_v1_conversations_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/conversations/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Conversation
     * @description Get a conversation with all its turns.
     *
     *     Args:
     *         session_id: Session identifier for the conversation
     *         conversation_repo: Injected conversation repository
     *         current_user: Authenticated user
     *
     *     Returns:
     *         ConversationDetailResponse with full conversation details
     *
     *     Raises:
     *         HTTPException: 404 if conversation not found or not owned by user
     */
    get: operations['get_conversation_api_v1_conversations__session_id__get']
    put?: never
    post?: never
    /**
     * Delete Conversation
     * @description Delete a conversation and all its turns.
     *
     *     This performs a hard delete. Turns are automatically deleted via
     *     CASCADE foreign key constraint.
     *
     *     Args:
     *         session_id: Session identifier for the conversation to delete
     *         conversation_repo: Injected conversation repository
     *         db: Database session
     *         current_user: Authenticated user
     *
     *     Returns:
     *         DeleteConversationResponse with deletion summary
     *
     *     Raises:
     *         HTTPException: 404 if conversation not found or not owned by user
     */
    delete: operations['delete_conversation_api_v1_conversations__session_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/feed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Feed
     * @description One page of ranked paper cards for a digest week (default: the newest built week).
     *
     *     Public: an anonymous caller gets the global digest under the default weights with no
     *     lifecycle state and no compute-profile match.
     */
    get: operations['get_feed_api_v1_feed_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Comprehensive health check for all services.
     *
     *     Checks:
     *     - Database connectivity and counts
     *     - LLM provider configuration
     *     - Embeddings API key presence (OpenAI through LiteLLM)
     *
     *     Returns:
     *         HealthResponse with status and service details
     */
    get: operations['health_check_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/cleanup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cleanup Orphaned Records
     * @description Clean up orphaned database records (processed papers with no chunks).
     */
    post: operations['cleanup_orphaned_records_api_v1_ops_cleanup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Bulk Ingest
     * @description Queue bulk ingestion of papers via arXiv IDs and/or search query.
     */
    post: operations['bulk_ingest_api_v1_ops_ingest_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/papers/{arxiv_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Paper
     * @description Delete a paper and its chunks. Protected by API key.
     */
    delete: operations['delete_paper_api_v1_ops_papers__arxiv_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/system/arxiv-searches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get System Searches
     * @description Read current system user arXiv search configuration.
     */
    get: operations['get_system_searches_api_v1_ops_system_arxiv_searches_get']
    /**
     * Update System Searches
     * @description Replace all system user arXiv searches. Idempotent PUT.
     */
    put: operations['update_system_searches_api_v1_ops_system_arxiv_searches_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Tasks
     * @description List all task executions (no user filter).
     */
    get: operations['list_tasks_api_v1_ops_tasks_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/tasks/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Task Status
     * @description Get task status by Celery task ID (no ownership check).
     */
    get: operations['get_task_status_api_v1_ops_tasks__task_id__get']
    put?: never
    post?: never
    /**
     * Revoke Task
     * @description Revoke a pending or running task (no ownership check).
     */
    delete: operations['revoke_task_api_v1_ops_tasks__task_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ops/users/{user_id}/tier': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update User Tier
     * @description Assign or change a user's tier. Protected by API key.
     */
    patch: operations['update_user_tier_api_v1_ops_users__user_id__tier_patch']
    trace?: never
  }
  '/api/v1/papers/{arxiv_id}/score': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Paper Score
     * @description The score breakdown for a paper; 202 with its metadata while it is unscored.
     *
     *     Public. A signed-in caller opening an unscored paper enqueues `score_paper_task`
     *     (which ingests the full text itself) behind a Redis `SET NX` lock keyed on the arXiv
     *     id, so repeated polls share one task; the task releases the lock on completion and
     *     the TTL is the backstop. An anonymous caller gets the metadata only: nothing is
     *     enqueued and no budget is spent. A paper unknown to the index is fetched from arXiv
     *     (404 when arXiv has no entry, 503 when arXiv is down) and stored as a metadata-only row.
     */
    get: operations['get_paper_score_api_v1_papers__arxiv_id__score_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/papers/{arxiv_id}/state': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Put Paper State
     * @description Set the caller's lifecycle state for a paper (upsert; one row per user + paper).
     */
    put: operations['put_paper_state_api_v1_papers__arxiv_id__state_put']
    post?: never
    /**
     * Delete Paper State
     * @description Clear the caller's lifecycle state for a paper.
     */
    delete: operations['delete_paper_state_api_v1_papers__arxiv_id__state_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Stream
     * @description Stream one turn of a paper-scoped conversation via Server-Sent Events.
     */
    post: operations['stream_api_v1_stream_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Me
     * @description Get current user info including tier, limits, usage, and the feed profile.
     */
    get: operations['get_me_api_v1_users_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/library': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Library
     * @description The caller's papers grouped by lifecycle state, as feed cards (ARX-29).
     */
    get: operations['get_library_api_v1_users_me_library_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/me/preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update Preferences
     * @description Set the onboarding profile (categories, compute profile, keywords).
     *
     *     Written under `preferences["feed_profile"]`; other keys in the JSONB (for example the
     *     system user's `arxiv_searches`) are preserved.
     */
    patch: operations['update_preferences_api_v1_users_me_preferences_patch']
    trace?: never
  }
  '/api/v1/webhooks/clerk': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Clerk Webhook
     * @description Handle Clerk webhook events (user.updated, user.deleted).
     *
     *     Authenticates via Svix signature verification, not Clerk JWT.
     */
    post: operations['clerk_webhook_api_v1_webhooks_clerk_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AvailableWeek */
    AvailableWeek: {
      /** Paper Count */
      paper_count: number
      /**
       * Week Start
       * Format: date
       */
      week_start: string
    }
    /**
     * BulkIngestRequest
     * @description Request to bulk-ingest papers via ops API.
     */
    BulkIngestRequest: {
      /**
       * Arxiv Ids
       * @description Specific arXiv IDs to ingest
       */
      arxiv_ids?: string[] | null
      /**
       * Categories
       * @description arXiv categories filter
       */
      categories?: string[] | null
      /**
       * Force Reprocess
       * @description Re-process existing papers
       * @default false
       */
      force_reprocess?: boolean
      /**
       * Max Results
       * @description Max papers for search query
       * @default 10
       */
      max_results?: number
      /**
       * Search Query
       * @description arXiv search query
       */
      search_query?: string | null
    }
    /**
     * BulkIngestResponse
     * @description Response from bulk ingestion.
     */
    BulkIngestResponse: {
      /** Task Ids */
      task_ids: string[]
      /** Tasks Queued */
      tasks_queued: number
    }
    /**
     * CitationsEventData
     * @description Data for citation graph from explore_citations tool.
     */
    CitationsEventData: {
      /**
       * Arxiv Id
       * @description arXiv ID of the explored paper
       */
      arxiv_id: string
      /**
       * Reference Count
       * @description Derived from references list length to prevent mismatches.
       */
      readonly reference_count: number
      /**
       * References
       * @description Reference titles/descriptions
       */
      references: string[]
      /**
       * Title
       * @description Title of the explored paper
       */
      title: string
    }
    /**
     * CleanupResponse
     * @description Response from cleanup operation.
     */
    CleanupResponse: {
      /** Deleted Papers */
      deleted_papers: components['schemas']['OrphanedPaper'][]
      /** Orphaned Papers Found */
      orphaned_papers_found: number
      /** Papers Deleted */
      papers_deleted: number
    }
    /**
     * ContentEventData
     * @description Data for content events with streaming tokens.
     */
    ContentEventData: {
      /**
       * Token
       * @description Generated token
       */
      token: string
    }
    /**
     * ConversationDetailResponse
     * @description Full conversation with all turns.
     */
    ConversationDetailResponse: {
      /**
       * Arxiv Id
       * @description Paper this thread is scoped to, if any
       */
      arxiv_id: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Session Id */
      session_id: string
      /** Title */
      title: string | null
      /** Turns */
      turns: components['schemas']['ConversationTurnResponse'][]
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ConversationListItem
     * @description Summary item for conversation list.
     */
    ConversationListItem: {
      /**
       * Arxiv Id
       * @description Paper this thread is scoped to, if any
       */
      arxiv_id: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Last Query
       * @description Preview of last user message
       */
      last_query: string | null
      /** Session Id */
      session_id: string
      /** Title */
      title: string | null
      /** Turn Count */
      turn_count: number
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ConversationListResponse
     * @description Paginated list of conversations.
     */
    ConversationListResponse: {
      /** Conversations */
      conversations: components['schemas']['ConversationListItem'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      /** Total */
      total: number
    }
    /**
     * ConversationTurnResponse
     * @description Response schema for a single conversation turn.
     */
    ConversationTurnResponse: {
      /** Agent Response */
      agent_response: string
      citations: components['schemas']['CitationsEventData'] | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Guardrail Score */
      guardrail_score: number | null
      /** Model */
      model: string
      /** Provider */
      provider: string
      /** Reasoning Steps */
      reasoning_steps: string[] | null
      /**
       * Retrieval Attempts
       * @default 1
       */
      retrieval_attempts: number
      /** Rewritten Query */
      rewritten_query: string | null
      /** Sources */
      sources: components['schemas']['SourceInfo'][] | null
      /** Turn Number */
      turn_number: number
      /** User Query */
      user_query: string
    }
    /**
     * DeleteConversationResponse
     * @description Response after deleting a conversation.
     */
    DeleteConversationResponse: {
      /** Session Id */
      session_id: string
      /** Turns Deleted */
      turns_deleted: number
    }
    /**
     * DeletePaperResponse
     * @description Response for delete paper endpoint.
     */
    DeletePaperResponse: {
      /** Arxiv Id */
      arxiv_id: string
      /** Chunks Deleted */
      chunks_deleted: number
      /**
       * Message
       * @default Paper and associated chunks deleted successfully
       */
      message?: string
      /** Title */
      title: string
    }
    /**
     * DimensionDetail
     * @description One rubric dimension for the breakdown: distribution, judgments, and its evidence.
     */
    DimensionDetail: {
      /**
       * Band
       * @enum {string}
       */
      band: 'LOW' | 'MED' | 'HIGH'
      /** Confidence */
      confidence: number
      /**
       * Dimension
       * @enum {string}
       */
      dimension: 'method_clarity' | 'resource_feasibility' | 'data_availability' | 'demand'
      /** Evidence */
      evidence: components['schemas']['EvidenceItem'][]
      /** Expected */
      expected: number
      /** Judgments */
      judgments: components['schemas']['Judgment'][]
      /** Level */
      level: number
      /** Max Level */
      max_level: number
      /** Probabilities */
      probabilities: {
        [key: string]: number
      }
      /** Reasoning */
      reasoning: string
      /** Score */
      score: number
    }
    /**
     * DoneEventData
     * @description Sentinel: stream is complete.
     */
    DoneEventData: Record<string, never>
    /**
     * ErrorDetail
     * @description Detailed error information.
     */
    ErrorDetail: {
      /**
       * Code
       * @description Machine-readable error code
       */
      code: string
      /**
       * Details
       * @description Additional error context
       */
      details: {
        [key: string]: unknown
      }
      /**
       * Message
       * @description Human-readable error message
       */
      message: string
    }
    /**
     * ErrorEventData
     * @description Data for error events.
     */
    ErrorEventData: {
      /**
       * Code
       * @description Error code if available
       */
      code: string | null
      /**
       * Error
       * @description Error message
       */
      error: string
    }
    /**
     * ErrorResponse
     * @description Standard error response format.
     * @example {
     *       "error": {
     *         "code": "ARXIV_API_ERROR",
     *         "details": {
     *           "arxiv_id": "2301.12345",
     *           "underlying_error": "HTTP 503"
     *         },
     *         "message": "Failed to fetch papers from arXiv"
     *       },
     *       "request_id": "req_abc123",
     *       "timestamp": "2024-12-15T10:30:00Z"
     *     }
     */
    ErrorResponse: {
      /** @description Error details */
      error: components['schemas']['ErrorDetail']
      /**
       * Request Id
       * @description Request ID for tracing
       */
      request_id: string | null
      /**
       * Timestamp
       * Format: date-time
       * @description Error timestamp
       */
      timestamp: string
    }
    /**
     * EvidenceItem
     * @description One quoted span from `score_evidence`.
     */
    EvidenceItem: {
      /** Kind */
      kind: string
      /** Source */
      source: string | null
      /** Text */
      text: string
    }
    /**
     * FeedItem
     * @description One card. The feed only emits scored papers; the library also carries papers whose
     *     score is missing (rubric bump, ops delete), so the score-derived fields are optional.
     */
    FeedItem: {
      /**
       * Compute Match
       * @description None when the caller has no compute profile (or is anonymous)
       */
      compute_match: boolean | null
      /**
       * Headline
       * @description '<Model family> for <task type>' from the stored attributes
       */
      headline: string | null
      /**
       * Keyword Match
       * @default false
       */
      keyword_match: boolean
      /**
       * Low Confidence
       * @description Dimensions whose confidence is below the threshold
       */
      low_confidence: ('method_clarity' | 'resource_feasibility' | 'data_availability' | 'demand')[]
      /**
       * Meta
       * @description Ordered truthy-only phrases: compute tier, data access, code, weights, pseudocode, hyperparameters. Never a negative claim.
       */
      meta: string[]
      paper: components['schemas']['FeedPaper']
      /** Scored At */
      scored_at: string | null
      scores: components['schemas']['FeedScores'] | null
      state: components['schemas']['UserPaperStateResponse'] | null
    }
    /**
     * FeedPaper
     * @description Paper identity as shown on a card.
     */
    FeedPaper: {
      /** Arxiv Id */
      arxiv_id: string
      /** Authors */
      authors: string[]
      /** Categories */
      categories: string[]
      /** Pdf Url */
      pdf_url: string
      /**
       * Published Date
       * Format: date-time
       */
      published_date: string
      /** Title */
      title: string
    }
    /**
     * FeedProfile
     * @description The onboarding profile stored under `users.preferences["feed_profile"]`.
     *
     *     Kept in its own key so it never collides with the system user's `arxiv_searches`.
     *     `weights` is reserved for per-user composite weights and is not settable via the API in
     *     v1 (ARX-9 sets categories / compute_profile / keywords).
     */
    FeedProfile: {
      /** Categories */
      categories: string[]
      /** Compute Profile */
      compute_profile: ('laptop' | 'single_gpu' | 'cloud') | null
      /** Keywords */
      keywords: string[]
      /**
       * Weights
       * @description Per-user composite weights; None means the defaults
       */
      weights: {
        [key: string]: number
      } | null
    }
    /**
     * FeedResponse
     * @description A page of the ranked feed for one digest week.
     */
    FeedResponse: {
      /** Available Weeks */
      available_weeks: components['schemas']['AvailableWeek'][]
      /** Categories Available */
      categories_available: string[]
      /** Items */
      items: components['schemas']['FeedItem'][]
      /** Limit */
      limit: number
      /** Offset */
      offset: number
      /** Total */
      total: number
      /**
       * Week Start
       * @description None when no digest has been built yet
       */
      week_start: string | null
    }
    /**
     * FeedScores
     * @description Derived per-dimension 0-100 sub-scores plus the read-time composite.
     */
    FeedScores: {
      /** Composite */
      composite: number
      /** Data Availability */
      data_availability: number | null
      /** Demand */
      demand: number | null
      /** Method Clarity */
      method_clarity: number | null
      /** Resource Feasibility */
      resource_feasibility: number | null
    }
    /**
     * HealthResponse
     * @description Health check response.
     */
    HealthResponse: {
      /** Services */
      services: {
        [key: string]: components['schemas']['ServiceStatus']
      }
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /** Timestamp */
      timestamp: string
      /** Version */
      version: string
    }
    /**
     * Judgment
     * @description One atomic Jev answer (a Noul, Choice, or Score) as asked by a dimension node.
     *
     *     `probabilities` keys are strings so the payload round-trips through JSONB unchanged
     *     (Noul: "yes"/"no"; Choice: option labels; Score: level numbers as strings).
     */
    Judgment: {
      /**
       * Answer
       * @description Argmax answer (bool for Nouls, label for Choices, level for Scores)
       */
      answer: string | number | boolean
      /**
       * Confidence
       * @description Concentration of the distribution (max probability)
       */
      confidence: number
      /**
       * Key
       * @description Question key, e.g. 'algorithm_given'
       */
      key: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'noul' | 'choice' | 'score'
      /**
       * Legend
       * @description Score level descriptions, in level order
       */
      legend: string[] | null
      /** Probabilities */
      probabilities: {
        [key: string]: number
      }
    }
    /**
     * LibraryResponse
     * @description The caller's papers grouped by lifecycle state, newest update first. Dismissed
     *     papers are feedback, not library entries, and are left out.
     */
    LibraryResponse: {
      /** Implementing */
      implementing: components['schemas']['FeedItem'][]
      /** Saved */
      saved: components['schemas']['FeedItem'][]
      /** Shipped */
      shipped: components['schemas']['FeedItem'][]
    }
    /**
     * MeResponse
     * @description Response for /users/me endpoint.
     */
    MeResponse: {
      /** Chats Used Today */
      chats_used_today: number
      /** Daily Chat Limit */
      daily_chat_limit: number | null
      /** Email */
      email: string | null
      /** First Name */
      first_name: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Last Name */
      last_name: string | null
      /**
       * Onboarded
       * @default false
       */
      onboarded: boolean
      preferences: components['schemas']['UserPreferences']
      tier: components['schemas']['UserTier']
    }
    /**
     * MetadataEventData
     * @description Data for metadata event with execution stats.
     */
    MetadataEventData: {
      /** Execution Time Ms */
      execution_time_ms: number
      /** Guardrail Score */
      guardrail_score: number | null
      /** Query */
      query: string
      /** Retrieval Attempts */
      retrieval_attempts: number
      /** Session Id */
      session_id: string | null
      /**
       * Turn Number
       * @default 0
       */
      turn_number: number
    }
    /**
     * OpsArxivSearchConfig
     * @description Configuration for a system-level arXiv search (ops only).
     */
    OpsArxivSearchConfig: {
      /**
       * Categories
       * @description arXiv categories to filter (e.g., cs.AI, cs.LG)
       */
      categories?: string[] | null
      /**
       * Enabled
       * @description Whether this search is active for scheduled runs
       * @default true
       */
      enabled?: boolean
      /**
       * Max Results
       * @description Maximum papers to fetch per run
       * @default 10
       */
      max_results?: number
      /**
       * Name
       * @description Display name for this search
       */
      name: string
      /**
       * Query
       * @description arXiv search query
       */
      query: string
    }
    /**
     * OrphanedPaper
     * @description Details of an orphaned paper.
     */
    OrphanedPaper: {
      /** Arxiv Id */
      arxiv_id: string
      /** Paper Id */
      paper_id: string
      /** Title */
      title: string
    }
    /**
     * PaperAttributesDetail
     * @description Product attributes (chips) plus the code-mention spans behind `code_released`.
     */
    PaperAttributesDetail: {
      /** Code Evidence */
      code_evidence: components['schemas']['EvidenceItem'][]
      code_released: components['schemas']['Judgment'] | null
      model_family: components['schemas']['Judgment'] | null
      task_type: components['schemas']['Judgment'] | null
    }
    /**
     * PaperMetadata
     * @description FeedPaper plus the abstract: the detail header and the 202 body.
     */
    PaperMetadata: {
      /** Abstract */
      abstract: string
      /** Arxiv Id */
      arxiv_id: string
      /** Authors */
      authors: string[]
      /** Categories */
      categories: string[]
      /** Pdf Url */
      pdf_url: string
      /**
       * Published Date
       * Format: date-time
       */
      published_date: string
      /** Title */
      title: string
    }
    /**
     * PaperScoreDetailResponse
     * @description GET /papers/{arxiv_id}/score when the paper is scored.
     */
    PaperScoreDetailResponse: {
      attributes: components['schemas']['PaperAttributesDetail']
      /** Compute Match */
      compute_match: boolean | null
      /** Dimensions */
      dimensions: components['schemas']['DimensionDetail'][]
      /** Headline */
      headline: string
      /** Low Confidence */
      low_confidence: ('method_clarity' | 'resource_feasibility' | 'data_availability' | 'demand')[]
      /** Meta */
      meta: string[]
      paper: components['schemas']['PaperMetadata']
      /** Rubric Version */
      rubric_version: string
      /**
       * Scored At
       * Format: date-time
       */
      scored_at: string
      scores: components['schemas']['FeedScores']
      state: components['schemas']['UserPaperStateResponse'] | null
    }
    /**
     * RevokeTaskResponse
     * @description Response when a task is revoked.
     */
    RevokeTaskResponse: {
      /**
       * Revoked
       * @description Whether the revoke was sent
       */
      revoked: boolean
      /**
       * Task Id
       * @description ID of the revoked task
       */
      task_id: string
      /**
       * Terminated
       * @description Whether termination was requested
       */
      terminated: boolean
    }
    /**
     * ScorePendingResponse
     * @description GET /papers/{arxiv_id}/score (202) while the paper is unscored.
     *
     *     A signed-in caller has on-demand scoring running (`task_id`); an anonymous caller gets
     *     the metadata only, with `task_id` None, since nothing is enqueued for them.
     */
    ScorePendingResponse: {
      /** Arxiv Id */
      arxiv_id: string
      paper: components['schemas']['PaperMetadata']
      /**
       * Status
       * @default pending
       * @constant
       */
      status: 'pending'
      /**
       * Task Id
       * @description None for anonymous callers: nothing was enqueued
       */
      task_id: string | null
    }
    /**
     * ServiceStatus
     * @description Status of an individual service.
     */
    ServiceStatus: {
      /**
       * Details
       * @default {}
       */
      details?: {
        [key: string]: unknown
      }
      /** Message */
      message: string
      /**
       * Status
       * @enum {string}
       */
      status: 'healthy' | 'unhealthy'
    }
    /**
     * SourceInfo
     * @description A retrieved source paper, as sent in the SOURCES event.
     */
    SourceInfo: {
      /** Arxiv Id */
      arxiv_id: string
      /** Authors */
      authors: string[]
      /** Pdf Url */
      pdf_url: string
      /** Published Date */
      published_date: string | null
      /** Relevance Score */
      relevance_score: number
      /** Title */
      title: string
      /** Was Graded Relevant */
      was_graded_relevant: boolean | null
    }
    /**
     * SourcesEventData
     * @description Data for sources event with retrieved documents.
     */
    SourcesEventData: {
      /**
       * Sources
       * @description Retrieved document sources
       */
      sources: components['schemas']['SourceInfo'][]
    }
    /**
     * StatusEventData
     * @description Data for status events indicating workflow progress.
     */
    StatusEventData: {
      /**
       * Details
       * @description Optional extra info (score, attempt number, etc.)
       */
      details: {
        [key: string]: unknown
      } | null
      /**
       * Message
       * @description Human-readable status message
       */
      message: string
      /**
       * Step
       * @description Current workflow step name
       */
      step: string
    }
    /**
     * StreamEvent
     * @description SSE event wrapper with event type and data.
     */
    StreamEvent: {
      /** Data */
      data:
        | components['schemas']['StatusEventData']
        | components['schemas']['ContentEventData']
        | components['schemas']['SourcesEventData']
        | components['schemas']['MetadataEventData']
        | components['schemas']['ErrorEventData']
        | components['schemas']['CitationsEventData']
        | components['schemas']['DoneEventData']
      event: components['schemas']['StreamEventType']
    }
    /**
     * StreamEventType
     * @description Types of SSE events emitted during streaming.
     * @enum {string}
     */
    StreamEventType: 'status' | 'content' | 'sources' | 'metadata' | 'error' | 'done' | 'citations'
    /**
     * StreamRequest
     * @description Request for one turn of a paper-scoped conversation.
     *
     *     Every conversation is scoped to one ingested paper (Phase 3). The scope is persisted on
     *     the conversation, so a follow-up that names a different paper is a 409.
     */
    StreamRequest: {
      /**
       * Arxiv Id
       * @description The ingested paper this conversation is scoped to
       */
      arxiv_id: string
      /**
       * Query
       * @description Question to ask
       */
      query: string
      /**
       * Session Id
       * @description Session UUID for conversation continuity
       */
      session_id?: string | null
    }
    /**
     * SystemSearchesResponse
     * @description Response containing system arXiv search configurations.
     */
    SystemSearchesResponse: {
      /**
       * Arxiv Searches
       * @description System arXiv search configurations
       */
      arxiv_searches?: components['schemas']['OpsArxivSearchConfig'][]
    }
    /**
     * TaskListItem
     * @description Single task in a task list response.
     */
    TaskListItem: {
      /**
       * Completed At
       * @description When the task completed
       */
      completed_at?: string | null
      /**
       * Created At
       * Format: date-time
       * @description When the task was created
       */
      created_at: string
      /**
       * Error
       * @description Error message if task failed
       */
      error?: string | null
      /**
       * Status
       * @description Current task status
       */
      status: string
      /**
       * Task Id
       * @description Celery task ID
       */
      task_id: string
      /**
       * Task Type
       * @description Type of the task
       */
      task_type: string
    }
    /**
     * TaskListResponse
     * @description Response for listing tasks.
     */
    TaskListResponse: {
      /**
       * Limit
       * @description Page size
       */
      limit: number
      /**
       * Offset
       * @description Page offset
       */
      offset: number
      /** Tasks */
      tasks: components['schemas']['TaskListItem'][]
      /**
       * Total
       * @description Total number of tasks
       */
      total: number
    }
    /**
     * TaskStatusResponse
     * @description Response for task status queries.
     */
    TaskStatusResponse: {
      /**
       * Created At
       * @description When the task was created
       */
      created_at?: string | null
      /**
       * Error
       * @description Error message if task failed (only included on failure)
       */
      error?: string | null
      /**
       * Ready
       * @description Whether the task has completed (success or failure)
       */
      ready: boolean
      /**
       * Result
       * @description Task result if completed successfully (only included on success)
       */
      result?: {
        [key: string]: unknown
      } | null
      /**
       * Status
       * @description Current task status
       * @enum {string}
       */
      status: 'queued' | 'pending' | 'started' | 'success' | 'failure' | 'retry' | 'revoked'
      /**
       * Task Id
       * @description Unique identifier for the task
       */
      task_id: string
      /**
       * Task Type
       * @description Type of the task
       */
      task_type?: string | null
    }
    /**
     * UpdatePreferencesRequest
     * @description PATCH /users/me/preferences body: the onboarding profile (ONBOARD-1).
     */
    UpdatePreferencesRequest: {
      /** Categories */
      categories: string[]
      /**
       * Compute Profile
       * @enum {string}
       */
      compute_profile: 'laptop' | 'single_gpu' | 'cloud'
      /** Keywords */
      keywords?: string[]
    }
    /**
     * UpdateSystemSearchesRequest
     * @description Request to update system arXiv searches.
     */
    UpdateSystemSearchesRequest: {
      /**
       * Arxiv Searches
       * @description Complete list of arXiv search configurations
       */
      arxiv_searches: components['schemas']['OpsArxivSearchConfig'][]
    }
    /**
     * UpdateTierRequest
     * @description Request to update a user's tier.
     */
    UpdateTierRequest: {
      /** Tier */
      tier: string
    }
    /**
     * UpdateTierResponse
     * @description Response after tier update.
     */
    UpdateTierResponse: {
      /** Email */
      email?: string | null
      /** Tier */
      tier: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /**
     * UserPaperStateRequest
     * @description PUT /papers/{arxiv_id}/state body.
     */
    UserPaperStateRequest: {
      /** Dismissal Reason */
      dismissal_reason?: string | null
      /** Repo Url */
      repo_url?: string | null
      /**
       * State
       * @enum {string}
       */
      state: 'saved' | 'dismissed' | 'implementing' | 'shipped'
    }
    /**
     * UserPaperStateResponse
     * @description A user's lifecycle state for one paper.
     */
    UserPaperStateResponse: {
      /** Dismissal Reason */
      dismissal_reason: string | null
      /** Repo Url */
      repo_url: string | null
      /**
       * State
       * @enum {string}
       */
      state: 'saved' | 'dismissed' | 'implementing' | 'shipped'
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * UserPreferences
     * @description The user-facing slice of `users.preferences` (the system user's keys are omitted).
     */
    UserPreferences: {
      feed_profile: components['schemas']['FeedProfile'] | null
    }
    /**
     * UserTier
     * @enum {string}
     */
    UserTier: 'free' | 'pro'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_conversations_api_v1_conversations_get: {
    parameters: {
      query: {
        /** @description Only threads scoped to this paper */
        arxiv_id: string
        limit?: number
        offset?: number
      }
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationListResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_conversation_api_v1_conversations__session_id__get: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationDetailResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_conversation_api_v1_conversations__session_id__delete: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeleteConversationResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_feed_api_v1_feed_get: {
    parameters: {
      query?: {
        /** @description Keep papers in any of these categories */
        category?: string[] | null
        include_dismissed?: boolean
        limit?: number
        /** @description Minimum composite */
        min_score?: number | null
        offset?: number
        /** @description Any date; snapped to the Monday of its week */
        week?: string | null
      }
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FeedResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  health_check_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  cleanup_orphaned_records_api_v1_ops_cleanup_post: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CleanupResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  bulk_ingest_api_v1_ops_ingest_post: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkIngestRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkIngestResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_paper_api_v1_ops_papers__arxiv_id__delete: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path: {
        arxiv_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeletePaperResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_system_searches_api_v1_ops_system_arxiv_searches_get: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemSearchesResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_system_searches_api_v1_ops_system_arxiv_searches_put: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSystemSearchesRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemSearchesResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_tasks_api_v1_ops_tasks_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: {
        'x-api-key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskListResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_task_status_api_v1_ops_tasks__task_id__get: {
    parameters: {
      query?: {
        include_result?: boolean
      }
      header?: {
        'x-api-key'?: string | null
      }
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskStatusResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  revoke_task_api_v1_ops_tasks__task_id__delete: {
    parameters: {
      query?: {
        terminate?: boolean
      }
      header?: {
        'x-api-key'?: string | null
      }
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RevokeTaskResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_user_tier_api_v1_ops_users__user_id__tier_patch: {
    parameters: {
      query?: never
      header?: {
        'x-api-key'?: string | null
      }
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTierRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UpdateTierResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_paper_score_api_v1_papers__arxiv_id__score_get: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path: {
        arxiv_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaperScoreDetailResponse']
        }
      }
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScorePendingResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  put_paper_state_api_v1_papers__arxiv_id__state_put: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path: {
        arxiv_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserPaperStateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserPaperStateResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  delete_paper_state_api_v1_papers__arxiv_id__state_delete: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path: {
        arxiv_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  stream_api_v1_stream_post: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StreamRequest']
      }
    }
    responses: {
      /** @description Server-sent events */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': components['schemas']['StreamEvent']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_me_api_v1_users_me_get: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_library_api_v1_users_me_library_get: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LibraryResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_preferences_api_v1_users_me_preferences_patch: {
    parameters: {
      query?: never
      header?: {
        Authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePreferencesRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  clerk_webhook_api_v1_webhooks_clerk_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error envelope */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
